export const eventsCatalog = [
  {
    id: 'wind-gust',
    name: 'Порывистый ветер',
    weight: 1,
    duration: [20, 40],
    effect: { windBoost: 0.4 },
    hint: 'Дрейф низколетящих усиливается',
  },
  {
    id: 'jammer',
    name: 'Зона помех',
    weight: 1,
    duration: [25, 45],
    effect: { trackQualityMul: 0.8, noise: 0.25 },
    hint: 'Качество треков хуже в секторе',
  },
  {
    id: 'phantoms',
    name: 'Ложные отметки',
    weight: 1,
    duration: [10, 15],
    effect: { phantomRate: 0.3 },
    hint: 'Появляются фантомы',
  },
  {
    id: 'clarity',
    name: 'Окно ясности',
    weight: 0.8,
    duration: [12, 20],
    effect: { trackQualityMul: 1.2, noise: -0.1 },
    hint: 'Детект улучшен',
  },
  {
    id: 'civilian',
    name: 'Гражданский объект',
    weight: 0.7,
    duration: [20, 30],
    effect: { spawnCivilian: true },
    hint: 'Не угроза, но отвлекает',
  },
  {
    id: 'masking-weather',
    name: 'Маскирующая погода',
    weight: 0.35,
    duration: [30, 60],
    effect: { trackQualityMul: 0.6, noise: 0.35 },
    hint: 'Обзор сильно ухудшен',
  },
  {
    id: 'hyper-strike',
    name: 'Очень быстрая цель',
    weight: 0.15,
    duration: [15, 20],
    effect: { spawnHyper: true },
    hint: 'Гиперцель на подлёте',
  },
  {
    id: 'system-glitch',
    name: 'Сбой системы',
    weight: 0.2,
    duration: [5, 8],
    effect: { updateSlow: true },
    hint: 'Частота обновлений падает',
  },
];
