export const threatProfiles = [
  {
    id: 'slow-drone',
    name: 'Малый дрон',
    speed: [30, 70],
    altitude: [0.3, 1.5],
    signature: [0.2, 0.35],
    maneuver: { turnRate: 12, accel: 8 },
    danger: 'LOW',
    notes: 'Медленный, низкий, слабая заметность, дрейфует на ветру',
    behavior: 'patrol',
  },
  {
    id: 'fast-uav',
    name: 'Скоростной БПЛА',
    speed: [90, 160],
    altitude: [0.6, 2.4],
    signature: [0.35, 0.5],
    maneuver: { turnRate: 20, accel: 14 },
    danger: 'MED',
    notes: 'Устойчивый курс, хорошая скорость',
    behavior: 'corridor',
  },
  {
    id: 'cruise',
    name: 'Крылатый тип',
    speed: [180, 260],
    altitude: [0.4, 1.2],
    signature: [0.45, 0.65],
    maneuver: { turnRate: 8, accel: 10 },
    danger: 'HIGH',
    notes: 'Низко и быстро, мало маневра',
    behavior: 'direct',
  },
  {
    id: 'glider',
    name: 'Планирующий объект',
    speed: [60, 110],
    altitude: [2.0, 4.5],
    signature: [0.25, 0.45],
    maneuver: { turnRate: 10, accel: 6 },
    danger: 'MED',
    notes: 'Высоко, затем снижение ближе к городу',
    behavior: 'descent',
  },
  {
    id: 'weather',
    name: 'Метео/помеха',
    speed: [15, 40],
    altitude: [0.5, 3.0],
    signature: [0.8, 1.0],
    maneuver: { turnRate: 18, accel: 5 },
    danger: 'LOW',
    notes: 'Высокая заметность, не всегда угроза',
    behavior: 'noise',
  },
  {
    id: 'hyper',
    name: 'Очень быстрая цель',
    speed: [400, 520],
    altitude: [0.7, 2.0],
    signature: [0.55, 0.7],
    maneuver: { turnRate: 18, accel: 30 },
    danger: 'CRITICAL',
    notes: 'Редкая гиперцель, короткое окно реакции',
    behavior: 'burst',
  },
];
